# Generated by Django 4.1.6 on 2023-02-10 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_book_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('1', 'очень плохо'), ('2', 'плохо'), ('3', 'пойдет'), ('4', 'нормально'), ('5', 'ништяк')], max_length=30)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_book', to='main.book')),
            ],
        ),
    ]
